export const AUDIT_EVENT_TYPES = [
  "login",
  "failed_login",
  "logout",
  "permission_change",
  "client_created",
  "client_edited",
  "client_record_accessed",
  "matter_created",
  "matter_edited",
  "matter_record_accessed",
  "matter_note_added",
  "document_accessed",
  "draft_created",
  "billing_line_item_created",
  "billing_line_item_edited",
  "invoice_created",
  "invoice_submitted_for_approval",
  "invoice_approved",
  "invoice_number_assigned",
  "invoice_sent",
  "invoice_cancelled",
  "invoice_corrected",
  "statement_snapshot_created",
  "statement_submitted_for_approval",
  "statement_approved",
  "statement_sent",
  "statement_corrected",
  "payment_import_changed",
  "financial_correction_created",
  "vat_treatment_overridden",
  "agent_action",
  "document_metadata_created",
  "document_uploaded",
  "document_downloaded",
  "timeline_event_created",
  "marketing_approved",
  "outreach_approved"
] as const;

export type AuditEventType = (typeof AUDIT_EVENT_TYPES)[number];

export const SENSITIVE_AUDIT_EVENT_TYPES: ReadonlySet<AuditEventType> = new Set([
  "login",
  "failed_login",
  "logout",
  "permission_change",
  "client_created",
  "client_edited",
  "client_record_accessed",
  "matter_created",
  "matter_edited",
  "matter_record_accessed",
  "matter_note_added",
  "document_accessed",
  "draft_created",
  "billing_line_item_created",
  "billing_line_item_edited",
  "invoice_created",
  "invoice_submitted_for_approval",
  "invoice_approved",
  "invoice_number_assigned",
  "invoice_sent",
  "invoice_cancelled",
  "invoice_corrected",
  "statement_snapshot_created",
  "statement_submitted_for_approval",
  "statement_approved",
  "statement_sent",
  "statement_corrected",
  "payment_import_changed",
  "financial_correction_created",
  "vat_treatment_overridden",
  "agent_action",
  "document_metadata_created",
  "document_uploaded",
  "document_downloaded",
  "timeline_event_created",
  "marketing_approved",
  "outreach_approved"
]);

export function isSensitiveAuditEvent(eventType: AuditEventType): boolean {
  return SENSITIVE_AUDIT_EVENT_TYPES.has(eventType);
}
